# Welcome to Sinai Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme: sinai 
# theme_version: 1.0.1

# Site settings
title:              Allison Burtch
logo:               # Logo image URL
description:        Art archive from 2010-2016
baseurl:            '/' # The subpath of your site, e.g. /blog
url:                'https://allisonburtch.github.io' # The base hostname & protocol for your site
twitter:            'https://twitter.com/irl'
# facebook:           https://www.facebook.com/aspirethemes
instagram:          'https://www.instagram.com/allisonburtch'

markdown:  kramdown
permalink: pretty
paginate:  20
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-paginate

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
